### ISSUE TITLE
How should I run visualizer "gpu_voxels_visualization -c configfile.xml" 

### ISSUE THREAD

**Issue by praveenneuron** [fzi-forschungszentrum-informatik/gpu-voxels#6]
After compiling succefully I am only able to run command line examples. How can I run visualizer. Also can you provide tutorial to run with ROS. That will be of great help to experiment.

**Comment by Squelsh** [comment]
The viewer connects to the provider via shared memory. Just open another console and start the viewer with `gpu_voxels_visualization -c configfile.xml`.

How would a ROS example help you? It is exactly the same API as in the example files. Just link against GPU Voxels with your ROS Node and you can use the API. You yourself will than have to take care on how to interact with the lib via ROS messages, services whatsoever.

Apart from that I am currentyl working on a URDF Parser for GPU Voxels, so that you can load ROS kinematics descriptions easily.

**Comment by praveenneuron** [comment]
URDF Parser for GPU Voxels would help. Can I know by when are you releasing it?

**Comment by Squelsh** [comment]
Just sign up for the mailing list and you will allways be informed about all updates.
Right now I can't tell you how long it will take to implement the stuff. Hopefully 1-2 weeks, depending on my workload.
